version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_TAG="v${CODEBUILD_RESOLVED_SOURCE_VERSION:-b${CODEBUILD_BUILD_NUMBER}}"
      - export IMAGE_TAG
      - echo "IMAGE_TAG=${IMAGE_TAG}"
      - echo "REPOSITORY_URI=${REPOSITORY_URI}"
      - REGISTRY=$(echo "$REPOSITORY_URI" | cut -d'/' -f1)
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
  build:
    commands:
      - docker build -t "${REPOSITORY_URI}:${IMAGE_TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${IMAGE_TAG}"
      - printf '{"ImageURI":"%s"}\n' "${REPOSITORY_URI}:${IMAGE_TAG}" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
